export {default as Navbar} from "./navbar/Navbar"
export {default as Header} from "./section/header/Header"
export {default as Project} from "./section/repo/Project"
export {default as Game} from "./section/game/Game"
export {default as About} from "./section/about/About"
export {default as Footer} from "./footer/Footer"